# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# EasyLinux - A beginner-friendly Fedora Atomic distribution
# Based on Kinoite (KDE Plasma) with immutable root filesystem
# Danish localization included

name: easylinux
description: A beginner-friendly Linux distribution inspired by SteamOS

# Base image: Kinoite is Fedora Atomic with KDE Plasma
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # ============================================
  # DANISH LOCALE FILES
  # ============================================
  - type: files
    files:
      - source: etc
        destination: /etc

  # ============================================
  # PACKAGE MANAGEMENT
  # ============================================
  - type: rpm-ostree
    install:
      # Danish language support
      - glibc-langpack-da
      - langpacks-da

      # Useful CLI tools
      - htop
      - fastfetch
      - fish

      # Hardware support
      - fwupd

      # Gaming support
      - gamescope
      - mangohud

  # ============================================
  # SET TIMEZONE TO COPENHAGEN
  # ============================================
  - type: script
    scripts:
      - set-danish-defaults.sh

  # ============================================
  # DEFAULT FLATPAKS
  # ============================================
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          name: flathub
          title: Flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        notify: true
        install:
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.gnome.Calculator
          - org.kde.okular
          - com.spotify.Client
          - md.obsidian.Obsidian
          - org.signal.Signal
          - com.discordapp.Discord
          - com.valvesoftware.Steam
          - io.github.flattool.Warehouse
