# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# EasyLinux - A beginner-friendly Fedora Atomic distribution
# Danish localization included

name: easylinux
description: A beginner-friendly Linux distribution inspired by SteamOS

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # ============================================
  # PACKAGE MANAGEMENT
  # ============================================
  - type: rpm-ostree
    install:
      # Danish language support
      - glibc-langpack-da
      - langpacks-da

      # Useful CLI tools
      - htop
      - fastfetch
      - fish

      # Hardware support
      - fwupd

      # Gaming support
      - gamescope
      - mangohud

  # ============================================
  # DANISH LOCALIZATION
  # ============================================
  - type: containerfile
    snippets:
      - |
        RUN echo "LANG=da_DK.UTF-8" > /etc/locale.conf && \
            echo "KEYMAP=dk" > /etc/vconsole.conf && \
            ln -sf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime && \
            mkdir -p /etc/X11/xorg.conf.d && \
            echo 'Section "InputClass"\n    Identifier "system-keyboard"\n    MatchIsKeyboard "on"\n    Option "XkbLayout" "dk"\nEndSection' > /etc/X11/xorg.conf.d/00-keyboard.conf && \
            mkdir -p /etc/skel/.config && \
            echo '[Layout]\nLayoutList=dk\nModel=pc105\nUse=true' > /etc/skel/.config/kxkbrc

  # ============================================
  # DEFAULT FLATPAKS
  # ============================================
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          name: flathub
          title: Flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        notify: true
        install:
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.gnome.Calculator
          - org.kde.okular
          - com.spotify.Client
          - md.obsidian.Obsidian
          - org.signal.Signal
          - com.discordapp.Discord
          - com.valvesoftware.Steam
          - io.github.flattool.Warehouse
