# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# EasyLinux - A beginner-friendly Fedora Atomic distribution
# Based on Kinoite (KDE Plasma) with immutable root filesystem

name: easylinux
description: A beginner-friendly Linux distribution inspired by SteamOS

# Base image: Kinoite is Fedora Atomic with KDE Plasma
# Using Universal Blue's image which includes better hardware support and codecs
base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

# Build modules - executed in order
modules:
  # ============================================
  # PACKAGE MANAGEMENT
  # ============================================
  - type: rpm-ostree
    # Install packages into the base image
    # Note: ublue base already includes multimedia codecs
    install:
      # Useful CLI tools
      - htop
      - fastfetch
      - fish

      # Hardware support
      - fwupd

      # Gaming support
      - gamescope
      - mangohud

  # ============================================
  # DEFAULT FLATPAKS
  # ============================================
  # These get installed on first boot (v2 format)
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          name: flathub
          title: Flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        notify: true
        install:
          # Essential apps for beginners
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.gnome.Calculator
          - org.kde.okular
          - com.spotify.Client
          - md.obsidian.Obsidian
          # Communication
          - org.signal.Signal
          - com.discordapp.Discord
          # Gaming - Steam as Flatpak for better compatibility
          - com.valvesoftware.Steam
          # Flatpak management tool
          - io.github.flattool.Warehouse
