# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# EasyLinux - Repair Cafe Edition
# A beginner-friendly Fedora Atomic distribution for repair cafes and maker spaces

name: easylinux
description: A beginner-friendly Linux distribution - Repair Cafe Edition

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # ============================================
  # SYSTEM PACKAGES
  # ============================================
  - type: rpm-ostree
    install:
      # Danish language support
      - glibc-langpack-da
      - langpacks-da

      # CLI tools
      - htop
      - fastfetch
      - fish
      - vim-enhanced
      - git

      # Hardware support
      - fwupd

      # Gaming
      - gamescope
      - mangohud

      # Theming
      - papirus-icon-theme

      # KWin X11 for proper window decorations
      - kwin-x11

      # Plymouth boot splash
      - plymouth-theme-spinner

      # Calamares first-boot wizard
      - calamares
      - console-setup

  # ============================================
  # BRANDING & THEMES
  # ============================================
  - type: containerfile
    snippets:
      # Download repair cafe wallpapers from Unsplash
      - |
        RUN mkdir -p /usr/share/repaircafe/wallpapers && \
            curl -sL "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/workshop-tools.jpg && \
            curl -sL "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/electronics-repair.jpg && \
            curl -sL "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/soldering-work.jpg && \
            curl -sL "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/vintage-tools.jpg && \
            curl -sL "https://images.unsplash.com/photo-1588508065123-287b28e013da?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/multimeter.jpg && \
            curl -sL "https://images.unsplash.com/photo-1518770660439-4636190af475?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/circuit-board.jpg && \
            curl -sL "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/workbench.jpg && \
            curl -sL "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/3d-printer.jpg && \
            curl -sL "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/maker-space.jpg && \
            curl -sL "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=3840&q=90" -o /usr/share/repaircafe/wallpapers/tool-wall.jpg && \
            chmod 644 /usr/share/repaircafe/wallpapers/*.jpg

      # Install full Steam Deck Vapor theme (complete look-and-feel)
      - |
        RUN curl -sL "https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/steamdeck-kde-presets-0.29-1-any.pkg.tar.zst" -o /tmp/steamdeck.tar.zst && \
            zstd -d /tmp/steamdeck.tar.zst && \
            tar -xf /tmp/steamdeck.tar -C /tmp && \
            cp -r /tmp/usr/share/color-schemes/* /usr/share/color-schemes/ && \
            cp -r /tmp/usr/share/plasma/desktoptheme/* /usr/share/plasma/desktoptheme/ && \
            cp -r /tmp/usr/share/plasma/look-and-feel/* /usr/share/plasma/look-and-feel/ && \
            mkdir -p /usr/share/wallpapers && \
            cp -r /tmp/usr/share/wallpapers/* /usr/share/wallpapers/ && \
            rm -rf /tmp/steamdeck* /tmp/usr /tmp/etc

      # Install Redmond 2K color scheme (Windows 2000 style)
      - |
        RUN printf '[ColorEffects:Disabled]\nColor=56,56,56\nColorAmount=0\nColorEffect=0\nContrastAmount=0.65\nContrastEffect=1\nIntensityAmount=0.1\nIntensityEffect=2\n\n[ColorEffects:Inactive]\nChangeSelectionColor=true\nColor=112,111,110\nColorAmount=0.025\nColorEffect=2\nContrastAmount=0.1\nContrastEffect=2\nEnable=false\n\n[Colors:Button]\nBackgroundAlternate=212,208,200\nBackgroundNormal=212,208,200\nDecorationFocus=0,0,128\nDecorationHover=10,36,106\nForegroundActive=0,0,0\nForegroundInactive=128,128,128\nForegroundLink=0,0,255\nForegroundNegative=255,0,0\nForegroundNeutral=255,128,0\nForegroundNormal=0,0,0\nForegroundPositive=0,128,0\nForegroundVisited=128,0,128\n\n[Colors:Selection]\nBackgroundAlternate=10,36,106\nBackgroundNormal=10,36,106\nDecorationFocus=10,36,106\nDecorationHover=10,36,106\nForegroundActive=255,255,255\nForegroundInactive=255,255,255\nForegroundLink=255,255,0\nForegroundNegative=255,0,0\nForegroundNeutral=255,128,0\nForegroundNormal=255,255,255\nForegroundPositive=0,255,0\nForegroundVisited=255,128,255\n\n[Colors:Tooltip]\nBackgroundAlternate=255,255,225\nBackgroundNormal=255,255,225\nForegroundNormal=0,0,0\n\n[Colors:View]\nBackgroundAlternate=245,245,245\nBackgroundNormal=255,255,255\nDecorationFocus=0,0,128\nDecorationHover=10,36,106\nForegroundActive=0,0,0\nForegroundInactive=128,128,128\nForegroundLink=0,0,255\nForegroundNegative=255,0,0\nForegroundNeutral=255,128,0\nForegroundNormal=0,0,0\nForegroundPositive=0,128,0\nForegroundVisited=128,0,128\n\n[Colors:Window]\nBackgroundAlternate=212,208,200\nBackgroundNormal=212,208,200\nDecorationFocus=0,0,128\nDecorationHover=10,36,106\nForegroundActive=0,0,0\nForegroundInactive=128,128,128\nForegroundLink=0,0,255\nForegroundNegative=255,0,0\nForegroundNeutral=255,128,0\nForegroundNormal=0,0,0\nForegroundPositive=0,128,0\nForegroundVisited=128,0,128\n\n[General]\nColorScheme=Redmond2K\nName=Redmond 2K\nshadeSortColumn=true\n\n[WM]\nactiveBackground=10,36,106\nactiveBlend=255,255,255\nactiveForeground=255,255,255\ninactiveBackground=128,128,128\ninactiveBlend=128,128,128\ninactiveForeground=212,208,200\n' > /usr/share/color-schemes/Redmond2K.colors

      # Danish locale and timezone
      - |
        RUN echo "LANG=da_DK.UTF-8" > /etc/locale.conf && \
            echo "KEYMAP=dk" > /etc/vconsole.conf && \
            ln -sf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime && \
            mkdir -p /etc/X11/xorg.conf.d && \
            printf 'Section "InputClass"\n    Identifier "system-keyboard"\n    MatchIsKeyboard "on"\n    Option "XkbLayout" "dk"\nEndSection\n' > /etc/X11/xorg.conf.d/00-keyboard.conf

      # KDE Plasma defaults - Full Steam Deck Vapor look-and-feel
      - |
        RUN mkdir -p /etc/skel/.config && \
            printf '[Layout]\nLayoutList=dk\nModel=pc105\nUse=true\n' > /etc/skel/.config/kxkbrc && \
            printf '[General]\nColorScheme=Vapor\n\n[Icons]\nTheme=breeze-dark\n\n[KDE]\nLookAndFeelPackage=com.valve.vapor.desktop\nwidgetStyle=Breeze\n' > /etc/skel/.config/kdeglobals && \
            printf '[Theme]\nname=Vapor\n' > /etc/skel/.config/plasmarc && \
            printf '[org.kde.kdecoration2]\nlibrary=org.kde.breeze\ntheme=__aurorae__svg__ActiveAccentFrame\nButtonsOnLeft=\nButtonsOnRight=IAX\nCloseOnDoubleClickOnMenu=false\n\n[WindowSwitcher]\nLayoutName=org.kde.breeze.desktop\n\n[DesktopSwitcher]\nLayoutName=org.kde.breeze.desktop\n\n[Effect-overview]\nBorderActivate=9\n\n[Effect-windowview]\nBorderActivateAll=7\n\n[Plugins]\nblurEnabled=true\ncontrastEnabled=true\nslideEnabled=false\n\n[Windows]\nBorderlessMaximizedWindows=true\n' > /etc/skel/.config/kwinrc && \
            printf '[KSplash]\nTheme=com.valve.vapor\n' > /etc/skel/.config/ksplashrc

      # Configure SDDM login screen
      - |
        RUN mkdir -p /etc/sddm.conf.d && \
            printf '[Theme]\nCurrent=breeze\n\n[General]\nInputMethod=\n' > /etc/sddm.conf.d/easylinux.conf

      # Configure Plymouth boot splash
      - |
        RUN plymouth-set-default-theme spinner 2>/dev/null || true

      # OS release branding
      - |
        RUN sed -i 's/PRETTY_NAME=.*/PRETTY_NAME="EasyLinux (Repair Cafe Edition)"/' /usr/lib/os-release && \
            sed -i 's/NAME=.*/NAME="EasyLinux"/' /usr/lib/os-release && \
            echo 'VARIANT="Repair Cafe Edition"' >> /usr/lib/os-release && \
            echo 'VARIANT_ID=repaircafe' >> /usr/lib/os-release

  # ============================================
  # CALAMARES FIRST-BOOT WIZARD
  # ============================================
  - type: containerfile
    snippets:
      # Copy Calamares configuration
      - |
        COPY calamares/settings.conf /usr/share/calamares-easylinux/settings.conf
        COPY calamares/modules/ /usr/share/calamares-easylinux/modules/
        COPY calamares/branding/ /usr/share/calamares-easylinux/branding/

      # Install firstboot service and setup script
      - |
        COPY calamares/setup.sh /usr/libexec/easylinux-firstboot/setup.sh
        COPY calamares/easylinux-firstboot.service /usr/lib/systemd/system/easylinux-firstboot.service
        RUN chmod +x /usr/libexec/easylinux-firstboot/setup.sh && \
            systemctl enable easylinux-firstboot.service

  # ============================================
  # DEFAULT FLATPAKS
  # ============================================
  - type: default-flatpaks
    configurations:
      - scope: system
        repo:
          name: flathub
          title: Flathub
          url: https://dl.flathub.org/repo/flathub.flatpakrepo
        notify: true
        install:
          # Essential apps
          - org.mozilla.firefox
          - org.libreoffice.LibreOffice
          - org.videolan.VLC
          - org.gnome.Calculator
          - org.kde.okular

          # Communication
          - com.spotify.Client
          - md.obsidian.Obsidian
          - org.signal.Signal
          - com.discordapp.Discord

          # Gaming
          - com.valvesoftware.Steam

          # Utilities
          - io.github.flattool.Warehouse
          - com.github.tchx84.Flatseal

          # Repair Cafe / Maker apps
          - org.kicad.KiCad
          - org.freecadweb.FreeCAD
          - org.blender.Blender
          - org.gimp.GIMP
          - org.inkscape.Inkscape
          - org.gnome.SimpleScan
